{include file="{$_top}/_subMenu.tpl"}
<section class="functionList">
	<div class="inr">
        <!-- nav class="reg">
            <ul>
                <li><a href="#list01"><img src="../common/img/function/icon_reg.svg"><span>会計機能</span></a></li>
                <li><a href="#list02"><img src="../common/img/function/icon_setting1.svg"><span>管理機能</span></a></li>
                <li><a href="#list03"><img src="../common/img/function/icon_setting2.svg"><span>設定・その他</span></a></li>
            </ul>
        </nav -->
		<div id="list01" class="list"> 
			<h2>会計機能</h2>
			<table class="outline">
                <thead>
                    <tr>
                        <th>機能名</th>
                        <td>説明</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>テーブル会計</th>
                        <td>テーブル毎に注文伝票を作って会計できます。</td>
                    </tr>
                    <tr>
                        <th>部門会計</th>
                        <td>テイクアウトや出前など商品単位で会計できます。</td>
                    </tr>
                    <tr>
                        <th>分割会計</th>
                        <td>現金、カード、電子マネーを併用してお会計できます。</td>
                    </tr>
                    <tr>
                        <th>個別会計</th>
                        <td>ランチ時や割り勘などで商品や金額毎に会計を分割できます。</td>
                    </tr>
                    <tr>
                        <th>合算会計</th>
                        <td>宴会などで注文をテーブル毎に行って会計をまとめることができます。</td>
                    </tr>
                    <tr>
                        <th>会計種別選択</th>
                        <td>会計する際にQR決済やクーポンなどを区別して集計できます。</td>
                    </tr>
                    <tr>
                        <th>単品値引き</th>
                        <td>注文の際に商品毎に値引きを設定できます。</td>
                    </tr>
                    <tr>
                        <th>合計/小計値引き</th>
                        <td>会計時に合計/小計から値引きを設定できます。(金額指定、割合どちらも可)</td>
                    </tr>
                    <tr>
                        <th>サービス料</th>
                        <td>会計時にサービス料が設定できます。</td>
                    </tr>
                    <tr>
                        <th>深夜料金</th>
                        <td>予め設定することで自動で深夜料金を加算できます。</td>
                    </tr>
                    <tr>
                        <th>会計前伝票</th>
                        <td>テーブル会計の時に便利な会計前伝票が発行できます。</td>
                    </tr>
                    <tr>
                        <th>領収書印刷</th>
                        <td>通常のレシートとは別に領収書の発行ができます。</td>
                    </tr>
                    <tr>
                        <th>精算レポートの印刷</th>
                        <td>当日の売上を集計した精算レポートをレジ本体で印刷できます。</td>
                    </tr>
                </tbody>
            </table>
		</div>

		<div id="list02" class="list"> 
			<h2>管理機能</h2>
			<table class="outline">
                <thead>
                    <tr>
                        <th>機能名</th>
                        <td>説明</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>トレーニングモード</th>
                        <td>導入時の操作確認や新しいスタッフのトレーニングが行えます。</td>
                    </tr>
                    <tr>
                        <th>本日の売上</th>
                        <td>レジ上で売上の詳細や客数、取引数をグラフによって確認できます。</td>
                    </tr>
                    <tr>
                        <th>契約情報の閲覧</th>
                        <td>ID・登録期限・店舗情報を確認できます。</td>
                    </tr>
                    <tr>
                        <th>開局/精算</th>
                        <td>開局・点検・精算の各処理を簡単に行えます。</td>
                    </tr>
                    <tr>
                        <th>担当者管理</th>
                        <td>レジを操作する担当者を管理、編集できます。</td>
                    </tr>
                    <tr>
                        <th>売上履歴</th>
                        <td>伝票毎の取引履歴、精算履歴を確認できます。</td>
                    </tr>
                    <tr>
                        <th>編集</th>
                        <td>売上履歴から商品やお会計方法を編集できます。</td>
                    </tr>
                    <tr>
                        <th>取消</th>
                        <td>過去のお会計を取り消すことができます。</td>
                    </tr>
                    <tr>
                        <th>レシート再印刷</th>
                        <td>過去に発行したレシートや領収書を再印刷することができます。</td>
                    </tr>
                    <tr>
                        <th>入出金</th>
                        <td>レジ内のお金で買い出しをする場合など、お会計以外での入金・出金情報を管理できます。</td>
                    </tr>
                    <tr>
                        <th>商品管理</th>
                        <td>商品名や価格、税率を管理できます。</td>
                    </tr>
                    <tr>
                        <th>部門管理</th>
                        <td>カテゴリー毎に商品を分けて管理できます。</td>
                    </tr>
                    <tr>
                        <th>お気に入り</th>
                        <td>よく出る商品をお気に入り登録することで素早くオーダーができます。</td>
                    </tr>
                    <tr>
                        <th>チャージ対象外</th>
                        <td>商品毎にチャージ料金適用の有無を設定できます。</td>
                    </tr>
                    <tr>
                        <th>残数</th>
                        <td>商品毎に残数を設定することにより、在庫切れ商品の注文を防ぎます。</td>
                    </tr>
                    <tr>
                        <th>商品説明</th>
                        <td>商品毎に説明を登録することで、お客様からの質問にもその場で回答できます。</td>
                    </tr>
                    <tr>
                        <th>テーブル管理</th>
                        <td>テーブル名の編集やテーブル数の増減、削除ができます。</td>
                    </tr>
                    <tr>
                        <th>タイマー設定</th>
                        <td>時間課金制や食べ飲み放題のあるお店にも対応します。</td>
                    </tr>
                    <tr>
                        <th>客数選択</th>
                        <td>テーブルに客数を設定することで詳細な客数管理を行えます。</td>
                    </tr>
                    <tr>
                        <th>顧客選択</th>
                        <td>テーブルモードで顧客を選択することにより、顧客毎のデータを取得できます。</td>
                    </tr>
                    <tr>
                        <th>端数値引き</th>
                        <td>会計時に1円単位のお釣りが出ないように設定できます。</td>
                    </tr>
                    <tr>
                        <th>両替</th>
                        <td>両替の際はボタン一つでドロワを開閉できます。</td>
                    </tr>
                </tbody>
            </table>
		</div>

		<div id="list03" class="list"> 
			<h2>設定・その他</h2>
			<table class="outline">
                <thead>
                    <tr>
                        <th>機能名</th>
                        <td>説明</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>テーブルモード</th>
                        <td>テーブルモードのON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>担当者</th>
                        <td>レジの担当者を設定することで誰が操作したのかを記録できます。</td>
                    </tr>
                    <tr>
                        <th>ネットワーク設定</th>
                        <td>有線、Wi-Fiのどちらで接続するかを選択できます。</td>
                    </tr>
                    <tr>
                        <th>データ同期</th>
                        <td>管理画面で編集したデータを同期させることでレジに反映します。</td>
                    </tr>
                    <tr>
                        <th>残数管理</th>
                        <td>残数管理のON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>原価管理</th>
                        <td>原価設定のON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>消費税設定</th>
                        <td>消費税設定のON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>画面デザイン</th>
                        <td>レジ画面の基調色を変更できます。</td>
                    </tr>
                    <tr>
                        <th>タイマー</th>
                        <td>タイマー機能ON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>通知</th>
                        <td>精算時のメール通知設定を登録できます。</td>
                    </tr>
                    <tr>
                        <th>セキュリティ</th>
                        <td>特定のスタッフのみがドロワ開閉できるようセキュリティロックできます。</td>
                    </tr>
                    <tr>
                        <th>精算レポート</th>
                        <td>精算時に出力する項目を選択できます。</td>
                    </tr>
                    <tr>
                        <th>消費税設定</th>
                        <td>内税、外税、小数点以下切上げ・下げ・四捨五入を設定できます。</td>
                    </tr>
                    <tr>
                        <th>チャージ設定</th>
                        <td>サービス料、深夜料金のON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>レシート印刷</th>
                        <td>レシート印刷の使用・不使用を設定できます。</td>
                    </tr>
                    <tr>
                        <th>信計</th>
                        <td>クレジットカード使用のON・OFF、カード会社を設定できます。</td>
                    </tr>
                </tbody>
            </table>
		</div>
    </div>
</section>
<!--
{include file="{$_top}/function/_planbanner.tpl"}
-->