{include file="{$_top}/_subMenu.tpl"}
<section class="functionList">
	<div class="inr">
        <!-- nav class="mng">
            <ul>
                <li><a href="#list01"><img src="../common/img/function/icon_sales.svg"><span>売上管理</span></a></li>
                <li><a href="#list02"><img src="../common/img/function/icon_setting2.svg"><span>設定・その他</span></a></li>
            </ul>
        </nav -->
		<div id="list01" class="list"> 
			<h2>売上管理</h2>
			<table class="outline">
                <thead>
                    <tr>
                        <th>機能名</th>
                        <td>説明</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>売上推移</th>
                        <td>日・月・曜日・時間帯別、昨対比の売上推移を確認できます。</td>
                    </tr>
                    <tr>
                        <th>グループ作成</th>
                        <td>時間帯別、曜日別にグループを作成できます。</td>
                    </tr>
                    <tr>
                        <th>ABC分析</th>
                        <td>商品・部門・テーブル別の売上を分析でき、その結果をCSVで出力します。</td>
                    </tr>
                    <tr>
                        <th>ABC分析グループ作成</th>
                        <td>商品のジャンル、売上などの指標を決めてグループが作成できます。</td>
                    </tr>
                    <tr>
                        <th>取引履歴</th>
                        <td>お会計毎の詳細を記録し、編集やCSVで出力できます。</td>
                    </tr>
                    <tr>
                        <th>取引変更一覧</th>
                        <td>お会計後に変更された情報を一覧で表示します。</td>
                    </tr>
                    <tr>
                        <th>顧客管理</th>
                        <td>顧客データの登録や編集、削除ができます。</td>
                    </tr>
                    <tr>
                        <th>顧客一括登録</th>
                        <td>顧客をCSVファイルに入力することで一括登録が行えます。</td>
                    </tr>
                    <tr>
                        <th>顧客登録フォーム</th>
                        <td>顧客登録フォームでは顧客毎の詳細を入力できます。</td>
                    </tr>
                    <tr>
                        <th>商品登録・管理</th>
                        <td>商品名や価格、税率を管理できます。</td>
                    </tr>
                    <tr>
                        <th>部門登録・管理</th>
                        <td>カテゴリー毎に商品を分けて管理できます。</td>
                    </tr>
                    <tr>
                        <th>テーブル管理</th>
                        <td>テーブルは名前の編集、数の増減や削除を行えます。</td>
                    </tr>
                    <tr>
                        <th>リアルタイム閲覧</th>
                        <td>注文の詳細や人数、入店時間を確認できます。</td>
                    </tr>
                    <tr>
                        <th>会計ソフト連携</th>
                        <td>売上データを弥生会計、freee、マネーフォワードに応じた形式でCSV出力できます。</td>
                    </tr>
                </tbody>
            </table>
		</div>

		<div id="list02" class="list"> 
			<h2>設定・その他</h2>
			<table class="outline">
                <thead>
                    <tr>
                        <th>機能名</th>
                        <td>説明</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>商品管理</th>
                        <td>商品名や価格、税率を管理できます。</td>
                    </tr>
                    <tr>
                        <th>部門管理</th>
                        <td>カテゴリー毎に商品を分けて管理できます。</td>
                    </tr>
                    <tr>
                        <th>担当者</th>
                        <td>レジの担当者を設定することで誰が操作したのかを記録できます。</td>
                    </tr>
                    <tr>
                        <th>レシート</th>
                        <td>ロゴ・フリーテキスト・店舗情報を設定できます。</td>
                    </tr>
                    <tr>
                        <th>通知</th>
                        <td>精算時のメール通知設定、通知先のメールアドレスを登録できます。</td>
                    </tr>
                    <tr>
                        <th>商品詳細</th>
                        <td>登録した商品毎に味付け等の詳細な注文内容を設定できます。</td>
                    </tr>
                    <tr>
                        <th>原価管理</th>
                        <td>原価設定のON・OFFを設定できます。</td>
                    </tr>
                    <tr>
                        <th>消費税</th>
                        <td>消費税設の内税・外税を設定できます。</td>
                    </tr>
                    <tr>
                        <th>チャージ</th>
                        <td>サービス料、深夜料金の使用をON・OFFに変更でき、率の設定を行えます。</td>
                    </tr>
                    <tr>
                        <th>契約情報</th>
                        <td>ID・登録期限・店舗情報を確認できます。</td>
                    </tr>
                    <tr>
                        <th>決算期設定</th>
                        <td>月別の売上推移は設定した期首月から開始します。</td>
                    </tr>
                    <tr>
                        <th>パスワード変更</th>
                        <td>管理画面のログインパスワードを変更できます。</td>
                    </tr>
                    <tr>
                        <th>3密モニター</th>
                        <td>店舗の空席状況をリアルタイム発信することで、お客様に混雑具合をお知らせできます。</td>
                    </tr>
                    <tr>
                        <th>テーブル管理</th>
                        <td>テーブルは名前の編集、数の増減や削除を行えます。</td>
                    </tr>
                </tbody>
            </table>
		</div>
    </div>
</section>
<!--
{include file="{$_top}/function/_planbanner.tpl"}
-->